### ISSUE TITLE
Consider kebab-casing

### ISSUE THREAD

**Issue by ab5tract** [tokuhirom/p6-Cookie-Baker#2]
Hey, this looks great!

My only question is whether it might be nice to provide the API with kebab case forms. So with 'bake-cookie' instead of 'bake_cookie'. This could be made available either directly, or via an adverb to 'use', a la "use Cookie::Baker :kebab".

This brings the module more inline with current Perl 6 best practices.

Keep up the awesome pace! :)

**Comment by tokuhirom** [comment]
thanks for your recommendation. i renamed these methods!

**Comment by ab5tract** [comment]
\o/ ! Thanks for this :D
